# Generated by Django 4.2.3 on 2023-08-18 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0002_directorgeneral_especialidad_laboratorio_ciudad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratorio',
            name='ciudad',
            field=models.CharField(default='Santiago', max_length=50),
        ),
        migrations.AlterField(
            model_name='laboratorio',
            name='pais',
            field=models.CharField(default='Chile', max_length=50),
        ),
    ]
